name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --legacy-peer-deps
          echo "Dependencies installed successfully"

      - name: Build client
        run: |
          echo "Building React application..."
          npm run build:client
          echo "Build completed successfully"

      - name: Verify build output
        run: |
          echo "Contents of dist/public:"
          ls -la dist/public/
          echo "Checking for required files:"
          test -f dist/public/index.html && echo "✅ index.html exists" || echo "❌ index.html missing"
          test -d dist/public/assets && echo "✅ assets directory exists" || echo "❌ assets directory missing"
          echo "Checking index.html content:"
          head -20 dist/public/index.html

      - name: Setup 404 page for SPA routing  
        run: |
          echo "Setting up 404.html for SPA routing..."
          if [ -f client/404.html ]; then
            cp client/404.html dist/public/404.html
            echo "✅ Copied custom 404.html"
          else
            cp dist/public/index.html dist/public/404.html
            echo "✅ Created 404.html from index.html"
          fi
          
      - name: Setup .nojekyll file
        run: |
          touch dist/public/.nojekyll
          echo "✅ Created .nojekyll file to disable Jekyll processing"

      - name: Final verification
        run: |
          echo "Final build verification:"
          echo "Total files in dist/public:"
          find dist/public -type f | wc -l
          echo "Directory structure:"
          tree dist/public/ || find dist/public/ -type d
          echo "File sizes:"
          du -sh dist/public/*

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4